#!/usr/bin/env python

import sys
import subprocess

def getDebUri(package):

   command = "apt-get install "+ package +" -y"+" --print-uris"
   p = subprocess.Popen(command, shell=True, stdout = subprocess.PIPE)

   out = p.stdout.readlines()

   fh = None
	
   try:
      fh = open("getter.sh","a")
      #fh.write("#!/bin/bash\n")
      fh.write("# Url for package " + package +"\n")
      for line in out:
	 if "http" in line:
	    tokens = line.split()
	    url = tokens[0].strip("'")+"\n"
	    fh.write(url)

   except EnvironmentError as err:
      print "Cannot open file"
   finally:
      if fh is not None:
	 fh.close()
	


def main():
   arglist = sys.argv
   arglist.pop(0)

   for package in arglist:
      print "Generating url list for package: " + package.strip()
      getDebUri(package.strip())

if __name__ == "__main__":
   main()
